# Generated by Django 5.0.4 on 2024-06-17 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_newscomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newscomment",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="newscomment",
            name="likes",
        ),
    ]
