# Generated by Django 5.0.4 on 2024-06-18 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_remove_newscomment_dislikes_remove_newscomment_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newscomment",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="newscomment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="newscomment_dislikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="newscomment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="newscomment_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
