# Generated by Django 5.0.4 on 2024-06-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_alter_newscomment_options_newscomment_dislikes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
