# Generated by Django 5.0.4 on 2024-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_newstag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, to="social.newstag"),
        ),
    ]
