# Generated by Django 5.0.4 on 2024-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_alter_news_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="social.eventtag"),
        ),
    ]
