# Generated by Django 5.0.4 on 2024-06-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0008_eventtag_alter_event_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscomment",
            name="tags",
            field=models.ManyToManyField(blank=True, to="social.newstag"),
        ),
    ]
