# Generated by Django 3.2.25 on 2024-06-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_newscomment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.event'),
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='social.event'),
        ),
    ]
