# Generated by Django 3.2.25 on 2024-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20240620_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='event',
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='threads', to='social.Event'),
        ),
    ]
