# Generated by Django 3.2.25 on 2024-06-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20240621_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='events',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
