# Generated by Django 5.0.6 on 2024-06-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0015_auto_20240621_2146"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodel",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_message",
                to="social.event",
            ),
        ),
        migrations.AlterField(
            model_name="messagemodel",
            name="body",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
