# Generated by Django 5.0.6 on 2024-06-22 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0016_messagemodel_event_alter_messagemodel_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventMessageModel",
        ),
    ]
