# Generated by Django 5.0.6 on 2024-06-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0017_delete_eventmessagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_notification",
                to="social.comment",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_notification",
                to="social.post",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_notification",
                to="social.threadmodel",
            ),
        ),
    ]
